TuitionManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tutor/', include('tutor.urls')),
    path('client/', include('client.urls')),
    path('tuition/', include('tuition.urls')),
]

client/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='client-home'),
    path('login/', views.login, name='client-login'),
    path('logout/', views.logout, name='client-logout'),
    path('profile/<int:profile_id>/', views.view_profile, name='client-profile'),
    path('ad/new/', views.new, name='client-new'),
    path('ad/<int:ad_id>/', views.view_ad, name='client-applicants'),
    path('ad/<int:ad_id>/accept/<int:user_id>/', views.accept, name='client-accept'),
    path('ad/<int:ad_id>/terminate/', views.terminate, name='client-terminate'),
    path('ad/<int:ad_id>/feedback/', views.feedback, name='client-feedback'),
    path('running/', views.running, name='client-running'),
    path('history/', views.history, name='client-history'),
    path('settings/', views.settings, name='client-settings'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home-page'),
    path('login/', views.login, name='login-page'),
    path('register/', views.register, name='register-action'),
]

client/models.py
from django.db import models
from tuition.models import Ad


class ClientFeedback(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    rating = models.IntegerField(verbose_name='Rating')
    feedback = models.TextField(verbose_name='Feedback')

    def __str__(self):
        return self.ad.title

tuition/models.py
from django.db import models
from users.models import User


class Ad(models.Model):
    ad_time = models.DateTimeField(auto_now=True, verbose_name='Ad time')
    title = models.CharField(max_length=1000, null=False, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    subjects = models.CharField(max_length=1000, null=False, verbose_name='Subjects')
    type = models.CharField(max_length=200, null=False, verbose_name='Type')
    grade = models.CharField(max_length=200, null=False, verbose_name='Class')
    gender = models.CharField(max_length=20, verbose_name='Gender')
    pref_gender = models.CharField(max_length=20, verbose_name='Preferred Gender')
    std_count = models.IntegerField(verbose_name='Student Count')
    time = models.CharField(max_length=200, verbose_name='Teaching Time')
    days = models.IntegerField(null=False, verbose_name='How many days a week')
    location = models.CharField(max_length=1000, null=False, verbose_name='Location')
    salary = models.IntegerField(null=False, verbose_name='Monthly Salary')
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    taken = models.BooleanField(default=False, verbose_name='Taken')  # Whether the job is taken
    timeout = models.DateTimeField(null=False, verbose_name='Run This Ad Until')  # The Ad will be available until that time

    def __str__(self):
        return self.title


class Question(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000, null=False, verbose_name='Question')

    def __str__(self):
        return self.question.__str__()


class Assignee(models.Model):  # taken = True
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, verbose_name="Ad")
    tutor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Tutor")
    from_date = models.DateField(null=False, verbose_name="Date Started")
    to_date = models.DateField(null=True, verbose_name="Date finished", blank=True)

    def __str__(self):
        return self.tutor.__str__()


class Proposal(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, verbose_name="Ad")
    tutor = models.ForeignKey(User, on_delete=models.CASCADE)
    proposal = models.TextField(null=True)
    date = models.DateField(auto_now=True, verbose_name="Date proposed")

    def __str__(self):
        return self.ad.__str__()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    proposal = models.ForeignKey(Proposal, on_delete=models.CASCADE)
    answer = models.TextField(verbose_name='Answer')

    def __str__(self):
        return self.question.__str__()

client/views.py
from django.contrib.auth import (
    authenticate,
    login as login_user,
    logout as logout_user
)
from users.models import User, Phone, Verification
from tuition.models import Ad, Assignee, Proposal, Question
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from .decorators import client_required
from time import time
import datetime
import os
from .models import ClientFeedback
from tutor.models import TutorFeedback


@client_required
def home(request):
    """Show only the ads posted by the client which are not timed out and not already taken"""
    return render(request, 'client/feed.html', context={
        'feed_list': get_feed_list(
            request,
            Ad.objects.filter(timeout__gte=timezone.now(), client=request.user, taken=False).order_by('-ad_time')
        ),
        'display_url': True,
        'client_home': 'active',
        'show_applicant_number': True,
    })


@client_required
def view_ad(request, ad_id):
    ad = Ad.objects.filter(pk=ad_id, client=request.user)
    if ad.exists():
        ad = ad[0]
        if ad.taken:
            proposals = False
            assignee = Assignee.objects.get(ad=ad)
            c_feedback = ClientFeedback.objects.filter(ad=ad)
            c_feedback = c_feedback[0] if c_feedback.exists() else False
            t_feedback = TutorFeedback.objects.filter(ad=ad)
            t_feedback = t_feedback[0] if t_feedback.exists() else False
            _running = assignee.to_date is None or assignee.to_date > timezone.now().date()
        else:
            proposals = Proposal.objects.filter(ad=ad_id)
            proposals = proposals if proposals.exists() else False
            assignee = False
            c_feedback = False
            t_feedback = False
            _running = False
        return render(request, 'client/view_ad.html', context={
            'feed': get_feed(request, ad),
            'proposals': proposals,
            'assignee': assignee,
            'c_feedback': c_feedback,
            't_feedback': t_feedback,
            'running': _running,
        })
    else:
        return redirect('client-home')


@client_required
def feedback(request, ad_id):
    ad = Ad.objects.filter(pk=ad_id, taken=True, client=request.user)
    if not ad.exists():
        return redirect('client-home')
    ad = ad[0]
    if request.POST:
        allowed_rating = [1, 2, 3, 4, 5]
        rating = int(request.POST.get('rating', ''))
        _feedback = request.POST.get('feedback', '')
        if rating not in allowed_rating:
            messages.error(request, 'Invalid rating.')
            return render(request, 'client/feedback.html', context={
                'feed': get_feed(request, ad),
                'feedback': _feedback,
            })
        if not ClientFeedback.objects.filter(ad=ad).exists():
            ClientFeedback.objects.create(ad=ad, rating=rating, feedback=_feedback)
        messages.success(request, 'Feedback added.')
        return redirect('client-applicants', ad.pk)
    else:
        return render(request, 'client/feedback.html', context={
            'feed': get_feed(request, ad),
        })


@client_required
def accept(request, ad_id, user_id):
    ad = Ad.objects.get(pk=ad_id, client=request.user)
    ad.taken = True
    Assignee.objects.create(ad=ad, tutor_id=user_id, from_date=timezone.now())
    ad.save()
    messages.success(request, 'Proposal is accepted successfully.')
    return redirect('client-applicants', ad.pk)


@client_required
def terminate(request, ad_id):
    ad = Assignee.objects.get(ad_id=ad_id, ad__client=request.user)
    ad.to_date = timezone.now()
    ad.save()
    messages.success(request, 'The tuition is terminated successfully!')
    return redirect('client-applicants', ad.pk)


@client_required
def new(request):
    if request.POST:
        std_genders = {
            'male': 'Male',
            'female': 'Female',
            'mixed': 'Mixed',
        }
        pref_genders = {
            'male': 'Male',
            'female': 'Female',
            'any': 'Any',
        }
        title = request.POST.get('title', False)
        description = request.POST.get('description', False)
        questions = request.POST.get('questions', False)
        subjects = request.POST.get('subjects', False)
        _type = request.POST.get('type', False)
        grade = request.POST.get('grade', False)
        gender = request.POST.get('gender', False)
        std_count = request.POST.get('std_count', False)
        pref_gender = request.POST.get('pref_gender', False)
        _time = request.POST.get('time', False)
        days = request.POST.get('days', False)
        location = request.POST.get('location', False)
        salary = request.POST.get('salary', False)
        timeout = request.POST.get('timeout', False)  # date FIXME: the date format may be wrong
        try:
            t_timeout = datetime.datetime.strptime(timeout, "%d/%m/%Y").date()
        except ValueError:
            t_timeout = False

        if title and description and subjects and _type and grade and std_genders.get(gender, False) and std_count and\
                pref_genders.get(pref_gender, False) and _time and days and location and salary and t_timeout:
            ad = Ad.objects.create(title=title, description=description, subjects=subjects, type=_type, grade=grade,
                                   gender=std_genders.get(gender, False), std_count=int(std_count),
                                   pref_gender=pref_genders.get(pref_gender, False), time=_time,
                                   days=int(days), location=location, salary=int(salary), client=request.user,
                                   timeout=t_timeout)
            if ad is not None:
                if questions:
                    questions = questions.split('\n')
                    for question in questions:
                        Question.objects.create(ad=ad, question=question)
                messages.success(request, 'Ad is successfully created!')
                return redirect('client-applicants', ad.pk)

        messages.error(request, 'Please fill out all the fields.')
        return render(request, 'client/new_ad.html', context={
            'title': title,
            'description': description,
            'subjects': subjects,
            'type': _type,
            'grade': grade,
            'gender': gender,
            'std_count': std_count,
            'pref_gender': pref_gender,
            'time': _time,
            'days': days,
            'location': location,
            'salary': salary,
            'timout': timeout,
        })
    else:
        return render(request, 'client/new_ad.html')


@client_required
def view_profile(request, profile_id):
    """View only tutor profile"""
    user = User.objects.filter(pk=profile_id, is_tutor=True)
    if user.exists():
        user = user[0]
        work_history = Assignee.objects.filter(tutor=user, to_date__lte=timezone.now())
        return render(request, 'client/view_profile.html', context={
            'profile': user,
            'education': user.education_set.all().order_by('-to_year'),
            'work_history': work_history,
            'profile_img': os.path.basename(user.profile_img),
        })
    else:
        redirect('client-home')


@client_required
def history(request):
    archived_list = []
    archived_jobs = Assignee.objects.filter(to_date__lte=timezone.now(), ad__client=request.user)
    for obj in archived_jobs:
        archived_list.append(obj.ad)
    timed_out_ads = Ad.objects.filter(timeout__lte=timezone.now(), taken=False, client=request.user)
    for obj in timed_out_ads:
        archived_list.append(obj)
    return render(request, 'client/history.html', context={
        'feed_archive': get_feed_list(request, archived_list),
        'client_history': 'active',
        'show_feedback': True,
        'display_url': True,
        'show_assignee': True,
        'whos_feedback': 'Your',
    })


@client_required
def running(request):
    """Show ads that are assigned by the client"""
    active_list = []
    active_jobs = Assignee.objects.filter(to_date__gt=timezone.now(), ad__client=request.user)
    for obj in active_jobs:
        active_list.append(obj.ad)
    active_jobs = Assignee.objects.filter(to_date__isnull=True, ad__client=request.user)
    for obj in active_jobs:
        active_list.append(obj.ad)
    return render(request, 'client/running.html', context={
        'feed_list': get_feed_list(request, active_list),
        'client_running': 'active',
        'show_end_job': True,
        'show_assignee': True,
        'display_url': True,
    })


@client_required
def settings(request):
    if request.POST:
        name = request.POST.get('full_name', '')
        bio = request.POST.get('bio', '')
        location = request.POST.get('location', '')
        gender = request.POST.get('gender', '')
        email1 = request.POST.get('email1', '')
        email2 = request.POST.get('email2', '')
        phone = request.POST.get('phone', '')
        old_pass = request.POST.get('old_password', '')
        pass1 = request.POST.get('password1', '')
        pass2 = request.POST.get('password2', '')
        doc_type = request.POST.get('document_type', '')
        user = User.objects.get(pk=request.user.pk)
        # Change name
        if name != '':
            user.name = name
        # Change bio
        if bio != '':
            user.bio = bio
        # Change location
        if location != '':
            user.location = location
        # Change gender
        if gender != '':
            if gender == 'male':
                user.gender = 'Male'
            elif gender == 'female':
                user.gender = 'Female'
        # Change password
        if old_pass != '':
            chk_user = authenticate(email=user.email, password=old_pass, is_active=True)

client/templates/client/base_client.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <title>Tuition Management System</title>
  <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">
</head>
<body style="background-color: cornsilk;">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-success">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'client-home' %}">Tuition Management System</a>
      <div class="">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'client-new' %}">Post Ad</a>
          </li>
        </ul>
      </div>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
              data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
              aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tutor-logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header style="padding-top: 56px">
    <div class="container">
      <div class="row">
        <nav class="col-md-3 col-lg-2 sidebar">
          <div class="position-fixed"> <!-- fix for xs devices -->
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link {{ client_home }}" href="{% url 'client-home' %}">
                  <i class="fa fa-home"></i>
                  Home
                  {% if client_home %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ client_running }}" href="{% url 'client-running' %}">
                  <i class="far fa-hourglass"></i>
                  Running
                  {% if client_running %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ client_history }}" href="{% url 'client-history' %}">
                  <i class="fa fa-history"></i>
                  History
                  {% if client_history %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ client_settings }}" href="{% url 'client-settings' %}">
                  <i class="fa fa-cog"></i>
                  Settings
                  {% if client_settings %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="col-md-9 main-section">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger">{{ message }}</div>
              {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
              {% endif %}
            {% endfor %}
          {% endif %}
        {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </header>
  {# imports #}
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/grayscale.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
</body>
</html>

client/templates/client/feed.html
{% extends 'client/base_client.html' %}

{% block content %}
    <h3 style="margin: 10px 0;">Your Ads</h3>
    {% for feed in feed_list %}
        {% include 'client/single_ad.inc.html' %}
    {% endfor %}
{% endblock content %}

client/templates/client/feedback.html
{% extends 'client/base_client.html' %}

{% block content %}
    <style>
    div.view-ad {
        margin-top: 1rem;
        margin-bottom: 10px;
    }
    </style>
    <div class="view-ad">
      {% include 'client/single_ad.inc.html' %}
    </div>
    <form method="post">
      {% csrf_token %}
      <label for="rating">Rating</label>
      <select class="form-control" name="rating" id="rating" required>
          <option value="" disabled selected>Choose</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
      </select><br>
      <label for="feedback">Feedback</label>
      <textarea class="form-control" name="feedback" id="feedback" placeholder="Enter a short feedback" rows="4">{{ feedback }}</textarea>
      <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock content %}

client/templates/client/history.html
{% extends 'client/base_client.html' %}

{% block content %}
    <div class="history">
      <h3>History</h3>
      {% if feed_archive|length %}
      {% for feed in feed_archive %}
        {% include 'client/single_ad.inc.html' %}
      {% endfor %}
      {% else %}
        <p>No history found.</p>
      {% endif %}
    </div>
{% endblock %}

client/templates/client/new_ad.html
{% extends 'client/base_client.html' %}

{% block content %}
    <h1>Post a New Ad</h1>
    <form method="POST">
      <fieldset class="form-group">
        {% csrf_token %}
        <label for="title" class="sr-only">Ad title</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Enter a title" value="{{ title }}" required>
        <label for="description" class="sr-only">Ad description</label>
        <textarea class="form-control" rows="5" id="description" name="description" placeholder="Enter a short description" required>{{ description }}</textarea>
        <label for="questions" class="sr-only">Enter optional question</label>
        <textarea class="form-control" rows="3" id="questions" name="questions" placeholder="Enter optional questions separated by new lines (ie. enter)" required>{{ questions }}</textarea>
        <label for="subjects" class="sr-only">Subjects to be taught</label>
        <input type="text" class="form-control" id="subjects" name="subjects" placeholder="Enter subjects to be taught" value="{{ subjects }}" required>
        <label for="type" class="sr-only">Version/Medium</label>
        <input type="text" class="form-control" id="type" name="type" placeholder="Enter version/medium (eg. Pilipino Medium, English Medium)" value="{{ type }}" required>
        <label for="grade" class="sr-only">Class</label>
        <input type="text" class="form-control" id="grade" name="grade" placeholder="Enter class (eg. Class 10, HSC prep, etc.)" value="{{ grade }}" required>
        Gender:
        <label><input type="radio" id="gender" name="gender" value="male" required> Male</label>
        <label><input type="radio" id="gender" name="gender" value="female" required> Female</label>
        <label><input type="radio" id="gender" name="gender" value="mixed" required> Mixed</label><br>
        <label for="std_count" class="sr-only">Student count</label>
        <input type="number" class="form-control" id="std_count" name="std_count" placeholder="Number of students" value="{{ std_count }}" required>
        Preferred gender for tutor:
        <label><input type="radio" id="pref_gender" name="pref_gender" value="male" required> Male</label>
        <label><input type="radio" id="pref_gender" name="pref_gender" value="female" required> Female</label>
        <label><input type="radio" id="pref_gender" name="pref_gender" value="any" required> Any</label><br>
        <label for="time" class="sr-only">Teaching time</label>
        <input type="text" class="form-control" id="time" name="time" placeholder="Teaching time (eg. 5.00 PM - 7:00 PM, Evening, etc)" value="{{ time }}" required>
        <label for="days" class="sr-only">How many days a week?</label>
        <input type="text" class="form-control" id="days" name="days" placeholder="How many days a week?" value="{{ days }}" required>
        <label for="location" class="sr-only">Tuition location</label>
        <input type="text" class="form-control" id="location" name="location" placeholder="Enter tuition location" value="{{ location }}" required>
        <label for="salary" class="sr-only">Salary per month</label>
        <input type="number" class="form-control" id="salary" name="salary" placeholder="Enter salary per month" value="{{ salary }}" required>
        <label for="timeout" class="sr-only">Run this until</label>
        <input type="date" class="form-control" id="timeout" name="timeout" placeholder="Enter a date until which the ad will run (dd/mm/yyyy)" value="{{ timout }}" required>
        <button type="submit" class="btn btn-dark">Submit</button>
      </fieldset>
    </form>
{% endblock content %}

client/templates/client/running.html
{% extends 'client/base_client.html' %}

{% block content %}
    <div class="history">
      <h3>Running Tuitions</h3>
      {% if feed_list|length %}
      {% for feed in feed_list %}
        {% include 'client/single_ad.inc.html' %}
      {% endfor %}
      {% else %}
        <p>No running tuitions.</p>
      {% endif %}
    </div>
{% endblock %}

client/templates/client/single_ad.inc.html
{% if feed.proposals and show_applicant_number %}
<div class="ad border-info card" style="border-top-width: thick;">
  <div class="bg-info card-text text-light" style="padding: 0 10px;">
    {{ feed.proposals }} applicant(s)
  </div>
{% else %}
<div class="ad card">
{% endif %}
  <div class="card-body">
    <h4 class="card-title">
    {% if display_url %}
        <a class="card-link" href="{% url 'client-applicants' feed.pk %}">{{ feed.title }}</a>
    {% else %}
        {{ feed.title }}
    {% endif %}
    </h4>
    <p class="card-text">{{ feed.description }}</p>
    <div class="row">
      <div class="col-md-6" title="Class and medium"><i class="fa fa-graduation-cap"></i> {{ feed.grade }} ({{ feed.type }})</div>
      <div class="col-md-6" title="Subjects"><i class="fa fa-book"></i> {{ feed.subjects }}</div>
    </div>
    <div class="row">
      <div class="col-md-6" title="Monthly salary"><i class="fa">৳</i> {{ feed.salary }}</div>
      <div class="col-md-6" title="Student gender and count"><i class="fa fa-user"></i> {{ feed.gender }} ({{ feed.std_count }} student(s))</div>
    </div>
    <div class="row">
      <div class="col-md-6" title="Date and time">
        <i class="fa fa-calendar-alt"></i>
        {{ feed.days }} days a week
        {% if feed.time %}
            ({{ feed.time }})
        {% endif %}
      </div>
      <div class="col-md-6" title="Location"><i class="fa fa-map-marked"></i> {{ feed.location }}</div>
    </div>
    {% with taken=feed.ad.taken %}
    {% if taken and show_assignee %}
      {% with assignee=feed.ad.assignee_set.first.tutor %}
        <div class="card-text">Assigned to <a href="{% url 'client-profile' assignee.pk %}" >{{ assignee.name }}</a></div>
      {% endwith %}
    {% endif %}
    {% if taken and show_end_job %}
        <a href="{% url 'client-terminate' feed.pk %}" class="btn btn-dark btn-small m-1">End tuition</a>
    {% endif %}
    {% if taken and show_feedback %}
      {% if not feed.feedback %}
        <a href="{% url 'client-feedback' feed.pk %}" class="btn btn-dark btn-small m-1">Provide feedback</a>
      {% else %}
        {% with feedback=feed.feedback %}
          {% include 'tutor/feedback.inc.html' %}
        {% endwith %}
      {% endif %}
    {% endif %}
    {% endwith %}
  </div>
</div>

client/templates/client/view_ad.html
{% extends 'client/base_client.html' %}

{% block content %}
    <style>
    div.view-ad {
        margin-top: 1rem;
        margin-bottom: 10px;
    }
    </style>
    <div class="view-ad">
      {% include 'client/single_ad.inc.html' %}
    </div>
    {% if proposals %}
    <div class="prop_parent">
      <div class="h5">{{ proposals.count }} proposal(s) received.</div>
      {% for proposal in proposals %}
      <a class="btn btn-light d-block text-left" data-toggle="collapse" href="#history_active" role="button"
         aria-expanded="false" aria-controls="history_active">{{ proposal.tutor.name }}</a>
      <div class="collapse" id="history_active">
        <div class="container">
          <p>{{ proposal.proposal }}</p>
          {% with answers=proposal.answer_set %}
          {% if answers %}
          <ol>
            {% for answer in answers.all %}
            <li><span class="font-weight-bold">{{ answer.question.question }}</span><br>{{ answer.answer }}</li>
            {% endfor %}
          </ol>
          {% endif %}
          {% endwith %}
          <a href="{% url 'client-profile' proposal.tutor.pk %}" class="btn btn-small btn-light">View profile</a>
          <a href="{% url 'client-accept' feed.pk proposal.tutor.pk %}" class="btn btn-small btn-dark">Accept</a>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endif %}
    {% if assignee %}
        <p>Assigned to <a href="{% url 'client-profile' assignee.tutor.pk %}">{{ assignee.tutor.name }}</a></p>
    {% endif %}
    {% if running %}
        <a href="{% url 'client-terminate' feed.pk %}" class="btn btn-dark btn-small m-1">End tuition</a>
    {% endif %}

    {% if c_feedback %}
    {% with feedback=c_feedback %}
    {% with whos_feedback='Your' %}
        {% include 'tutor/feedback.inc.html' %}
    {% endwith %}
    {% endwith %}
    {% elif assignee and not running %}
        <a href="{% url 'client-feedback' feed.pk %}" class="btn btn-dark btn-small m-1">Provide feedback</a>
    {% endif %}
    {% if t_feedback %}
    {% with feedback=t_feedback %}
    {% with whos_feedback="Tutor's" %}
        {% include 'tutor/feedback.inc.html' %}
    {% endwith %}
    {% endwith %}
    {% endif %}
{% endblock content %}

client/templates/client/view_profile.html
{% extends 'client/base_client.html' %}
{% load static %}

{% block content %}
{% include 'tutor/tutor_profile.inc.html' %}
{% endblock content %}