TuitionManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tutor/', include('tutor.urls')),
    path('client/', include('client.urls')),
    path('tuition/', include('tuition.urls')),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home-page'),
    path('login/', views.login, name='login-page'),
    path('register/', views.register, name='register-action'),
]

tutor/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.feed, name='tutor-home'),
    path('feed/', views.feed, name='tutor-feed'),
    path('apply/<int:ad_id>/', views.apply, name='tutor-apply'),
    path('feedback/<int:ad_id>/', views.feedback, name='tutor-feedback'),
    path('profile/<int:profile_id>/', views.view_profile, name='tutor-profile'),
    path('profile/<int:profile_id>/edit', views.edit_profile, name='tutor-edit-profile'),
    path('history/', views.history, name='tutor-history'),
    path('settings/', views.settings, name='tutor-settings'),
    path('logout/', views.logout, name='tutor-logout'),
    path('login/', views.login, name='tutor-login'),
]

client/models.py
from django.db import models
from tuition.models import Ad


class ClientFeedback(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    rating = models.IntegerField(verbose_name='Rating')
    feedback = models.TextField(verbose_name='Feedback')

    def __str__(self):
        return self.ad.title

tuition/models.py
from django.db import models
from users.models import User


class Ad(models.Model):
    ad_time = models.DateTimeField(auto_now=True, verbose_name='Ad time')
    title = models.CharField(max_length=1000, null=False, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    subjects = models.CharField(max_length=1000, null=False, verbose_name='Subjects')
    type = models.CharField(max_length=200, null=False, verbose_name='Type')
    grade = models.CharField(max_length=200, null=False, verbose_name='Class')
    gender = models.CharField(max_length=20, verbose_name='Gender')
    pref_gender = models.CharField(max_length=20, verbose_name='Preferred Gender')
    std_count = models.IntegerField(verbose_name='Student Count')
    time = models.CharField(max_length=200, verbose_name='Teaching Time')
    days = models.IntegerField(null=False, verbose_name='How many days a week')
    location = models.CharField(max_length=1000, null=False, verbose_name='Location')
    salary = models.IntegerField(null=False, verbose_name='Monthly Salary')
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    taken = models.BooleanField(default=False, verbose_name='Taken')  # Whether the job is taken
    timeout = models.DateTimeField(null=False, verbose_name='Run This Ad Until')  # The Ad will be available until that time

    def __str__(self):
        return self.title


class Question(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    question = models.CharField(max_length=1000, null=False, verbose_name='Question')

    def __str__(self):
        return self.question.__str__()


class Assignee(models.Model):  # taken = True
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, verbose_name="Ad")
    tutor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Tutor")
    from_date = models.DateField(null=False, verbose_name="Date Started")
    to_date = models.DateField(null=True, verbose_name="Date finished", blank=True)

    def __str__(self):
        return self.tutor.__str__()


class Proposal(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, verbose_name="Ad")
    tutor = models.ForeignKey(User, on_delete=models.CASCADE)
    proposal = models.TextField(null=True)
    date = models.DateField(auto_now=True, verbose_name="Date proposed")

    def __str__(self):
        return self.ad.__str__()


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    proposal = models.ForeignKey(Proposal, on_delete=models.CASCADE)
    answer = models.TextField(verbose_name='Answer')

    def __str__(self):
        return self.question.__str__()

tutor/models.py
from django.db import models
from tuition.models import Ad


class TutorFeedback(models.Model):
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    rating = models.IntegerField(verbose_name='Rating')
    feedback = models.TextField(verbose_name='Feedback')

    def __str__(self):
        return self.ad.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class UserManager(BaseUserManager):
    def create_user(self, name, email, user_type, password):
        if not email:
            raise ValueError('Email must be specified!')

        user = self.model(
            name=name,
            email=self.normalize_email(email),
        )
        if user_type == 'client':
            user.is_client = True
        elif user_type == 'tutor':
            user.is_tutor = True
        else:
            raise ValueError('User type can be either client or tutor')

        user.set_password(password)
        user.save(self._db)
        return user

    def create_superuser(self, name, email, password):
        if not email:
            raise ValueError('Email must be specified!')

        user = self.model(
            name=name,
            email=self.normalize_email(email),
        )
        user.is_admin = True
        user.set_password(password)
        user.save(self._db)
        return user


class User(AbstractBaseUser):
    """The user model, it is a user profile as well"""
    email = models.EmailField(
        verbose_name='Email address',
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)
    is_tutor = models.BooleanField(default=False)
    name = models.CharField(max_length=100, null=False, verbose_name='Full name')
    bio = models.CharField(max_length=1000, verbose_name='Bio')
    location = models.CharField(max_length=1000, verbose_name='Location')
    gender = models.CharField(max_length=20, verbose_name='Gender')
    title = models.CharField(max_length=1000, verbose_name='Overview title')  # Overview title
    overview = models.TextField(verbose_name='Overview')
    expertise = models.CharField(max_length=1000, verbose_name='Expertise')
    profile_img = models.TextField(verbose_name='Profile Image', blank=True)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['name']

    objects = UserManager()

    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        return self.is_admin

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        return True

    def has_module_perms(self, app_label):
        """"Does the user have permissions to view the app `app_label`?"""
        return True

    def __str__(self):
        return self.email


class Phone(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone_no = models.CharField(max_length=20, null=False)

    def __str__(self):
        return '{} - {}'.format(self.user.email, self.phone_no)


class Education(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    institute = models.CharField(max_length=200, null=False, verbose_name='Institute')
    department = models.CharField(max_length=200, verbose_name='Department')
    degree = models.CharField(max_length=200, verbose_name='Degree')
    result = models.CharField(max_length=200, verbose_name='Result')
    from_year = models.DateField(null=False, verbose_name='From year')
    to_year = models.DateField(null=False, verbose_name='To year')

    def __str__(self):
        return self.institute


class Verification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    type = models.CharField(max_length=50, verbose_name='File Type')
    file = models.TextField(verbose_name='File location')
    verified = models.BooleanField(verbose_name='Verified', default=False)

    def __str__(self):
        return '{} - {}'.format(self.user.email, self.type)

tutor/templates/tutor/apply.html
{% extends 'tutor/base_tutor.html' %}

{% block content %}
    <style>
    div.apply-form form {
        margin-top: 1rem;
        margin-bottom: 10px;
    }
    </style>
    <div class="apply-form">
      {% include 'tutor/single_ad.inc.html' %}
    {% if feed.already_applied %}
      <h5 class="font-weight-bold">Proposal</h5>
      <p>{{ feed.proposal }}</p>
      {% if feed.answers.count %}
        <h5 class="font-weight-bold">Questions asked by the client:</h5>
        <ol>
        {% for val in feed.answers.all %}
          <li><span class="font-weight-bold">{{ val.question }}</span><br>{{ val.answer }}</li>
        {% endfor %}
        </ol>
      {% endif %} {# end qa #}
    {% else %}
      <form method="post">
        {% csrf_token %}
        <textarea class="form-control" name="proposal" placeholder="Write a proposal (optional)"></textarea>
        {% if feed.questions.count %}
          <p>Questions asked by the client:</p>
          {% for val in feed.questions.all %}
            <textarea class="form-control" name="q_{{ val.pk }}" placeholder="{{ val }}" required></textarea>
          {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-dark">Apply</button>
      </form>
    {% endif %} {# end is_applied #}
    </div>
{% endblock content %}

tutor/templates/tutor/base_tutor.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <title>Tuition Management System</title>

    <link href="{% static 'css/grayscale.min.css' %}" rel="stylesheet">
  </head>
  <body style="background-color: cornsilk;">
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-success">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'tutor-feed' %}">Tuition Management System</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tutor-logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <header style="padding-top: 56px">
    <div class="container">
      <div class="row">
        <nav class="col-md-3 col-lg-2 sidebar">
          <div class="position-fixed"> <!-- fix for xs devices -->
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link {{ tutor_feed }}" href="{% url 'tutor-feed' %}">
                  <i class="fa fa-home"></i>
                  Feed
                  {% if tutor_feed %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ tutor_profile }}" href="{% url 'tutor-profile' user.pk %}">
                  <i class="fa fa-user"></i>
                  Profile
                  {% if tutor_profile %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ tutor_history }}" href="{% url 'tutor-history' %}">
                  <i class="fa fa-history"></i>
                  History
                  {% if tutor_history %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link {{ tutor_settings }}" href="{% url 'tutor-settings' %}">
                  <i class="fa fa-cog"></i>
                  Settings
                  {% if tutor_settings %}
                  <span class="sr-only">(current)</span>
                  {% endif %}
                </a>
              </li>
            </ul>
          </div>
        </nav>
        <div class="col-md-9 main-section">
          {% if messages %}
            {% for message in messages %}
              {% if message.tags == 'error' %}
                <div class="alert alert-danger">{{ message }}</div>
              {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
              {% endif %}
            {% endfor %}
          {% endif %}
        {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </header>
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

tutor/templates/tutor/client_profile.html
{% extends 'tutor/base_tutor.html' %}
{% load static %}

{% block content %}
    <style>
    .user-profile {
        margin: 10px 0;
    }
    .user-profile .user-image {
        height: 8rem;
        width: 8rem;
        border-radius: 50%;
    }

    #about div.collapse {
        display: block;
        height: 45px;
        overflow: hidden;
    }

    #about div.collapse.show {
        display: block;
        height: 100%;
        overflow: hidden;
    }

    #about div.collapsing[aria-expanded="false"] {
        height: 45px;
    }

    #about a.collapsed  {
        display: block;
        margin-top: 10px;
    }

    #about a.collapsed:after  {
        content: 'More';
    }

    #about a:not(.collapsed):after {
        content: 'Less';
    }
    </style>
    <div class="user-profile card">
      <div class="card-header">
        <table>
          <tr>
            <td style="padding-right: 15px">
              <img class="card-img user-image" src="/static/profile_imgs/{{ profile_img }}" alt="A portrait of {{ profile.name }}" />
            </td>
            <td>
              <h1 class="card-title">
                  {{ profile.name }}
                  {% if profile.verification_set.first.verified %}
                      <i class="text-info fas fa-check-circle" title="Verified Client"></i>
                  {% endif %}
              </h1>
              <h6 class="card-text"><i class="fa fa-graduation-cap"></i> {{ profile.bio }}</h6>
              <h6 class="card-text"><i class="fa fa-map-marked"></i> {{ profile.location }}</h6>
              <h6 class="card-text"><i class="fa fa-user"></i> {{ profile.gender }}</h6>
            </td>
          </tr>
        </table>
      </div>
      <div id="work_history" class="card-body">
        <h4 class="card-title hr">Tuition History</h4>
      {% if work_history %}
        {% for work in work_history %}
        <div class="card">
          <div class="card-body">
            <table class="w-100">
              <tr>
                <td>
                  <h6 class="card-title">{{ work.title }}</h6>
                  {% with assignee=work.assignee_set.first %}
                  <p class="card-text small">{{ assignee.from_date|date:"M Y" }} - {{ assignee.to_date|date:"M Y" }},
                    {{ work.std_count }} student(s), {{ work.days }} days a week<br>
                    {{ work.grade }} ({{ work.type }}), {{ work.subjects }}
                  </p>
                  {% endwith %}
                </td>
                <td class="text-right">Salary<br><i class="fa">৳</i>{{ work.salary }}</td>
              </tr>
            </table>
            <div class="feedback">
              {% with feedback=work.tutorfeedback_set.first %}
                {% if feedback %}
                    <hr>
                    {% include 'tutor/feedback.inc.html' %}
                {% endif %}
              {% endwith %}
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <p>No history found.</p>
      {% endif %}
      </div>
    </div>
{% endblock content %}

tutor/templates/tutor/feed.html
{% extends 'tutor/base_tutor.html' %}

{% block content %}
    <h3 style="margin: 10px 0;">Feed</h3>
    {% for feed in feed_list %}
        {% include 'tutor/single_ad.inc.html' %}
    {% endfor %}
{% endblock content %}

tutor/templates/tutor/feedback.html
{% extends 'tutor/base_tutor.html' %}

{% block content %}
    <style>
    div.view-ad {
        margin-top: 1rem;
        margin-bottom: 10px;
    }
    </style>
    <div class="view-ad">
      {% include 'tutor/single_ad.inc.html' %}
    </div>
    <form method="post">
      {% csrf_token %}
      <label for="rating">Rating</label>
      <select class="form-control" name="rating" id="rating" required>
          <option value="" disabled selected>Choose</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
      </select><br>
      <label for="feedback">Feedback</label>
      <textarea class="form-control" name="feedback" id="feedback" placeholder="Enter a short feedback" rows="4">{{ feedback }}</textarea>
      <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock content %}

tutor/templates/tutor/feedback.inc.html
<p class="card-text small">
  <span class="text-muted">{{ whos_feedback }} Feedback:</span><br>
  {# Print filled stars #}
  {% with ''|center:feedback.rating as range %}
  {% for _ in range %}
    <i class="fas fa-star"></i>
  {% endfor %}
  {% endwith %}
  {# Print empty stars #}
  {% with inv_rating=-5|add:feedback.rating %}
  {% widthratio inv_rating 1 -1 as inv_rating_p %}
  {% with ''|center:inv_rating_p as range %}
  {% for _ in range %}
    <i class="far fa-star"></i>
  {% endfor %}
  {% endwith %}
  {% endwith %}
  {{ feedback.rating }} star<br>
  {{ feedback.feedback }}</p>

tutor/templates/tutor/history.html
{% extends 'tutor/base_tutor.html' %}

{% block content %}
    <div class="history">
        <h3>History</h3>
        <div class="history-active" style="margin-bottom: 10px">
            <a class="btn btn-light d-block text-left" data-toggle="collapse" href="#history_active" role="button" aria-expanded="false" aria-controls="history_active">
                Active <span class="badge badge-dark badge-pill" style="padding-top: 3px">{{ feed_active.count }}</span>
            </a>
            <div class="collapse" id="history_active">
                <div class="container">
                    {% for feed in feed_active.list %}
                        {% include 'tutor/single_ad.inc.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
      {% with show_feedback=True %}
        <div class="history-archive">
            <a class="btn btn-light d-block text-left" data-toggle="collapse" href="#history_archive" role="button" aria-expanded="false" aria-controls="history_archive">
                Archive <span class="badge badge-dark badge-pill" style="padding-top: 3px">{{ feed_archive.count }}</span>
            </a>
            <div class="collapse" id="history_archive">
                <div class="container">
                    {% for feed in feed_archive.list %}
                        {% include 'tutor/single_ad.inc.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
      {% endwith %}
    </div>
{% endblock %}

tutor/templates/tutor/settings.html
{% extends 'tutor/base_tutor.html' %}

{% block content %}
    <div class="settings" style="margin: 10px 0;">
      <h3>Settings</h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend>Change Email/Phone</legend>
          <label for="old_email" class="sr-only">Old email</label>
          <input type="email" name="old_email" id="old_email" class="form-control" value="{{ email }}" disabled />
          <label for="email1" class="sr-only">New email</label>
          <input type="email" name="email1" id="email1" class="form-control" placeholder="New email address" />
          <label for="email2" class="sr-only">Confirm new email</label>
          <input type="email" name="email2" id="email2" class="form-control" placeholder="Confirm new email address" />
        {% if phone %}
          <label for="old_phone" class="sr-only">Old phone number</label>
          <input type="text" name="old_phone" id="old_phone" class="form-control" value="{{ phone }}" disabled />
        {% endif %}
          <label for="phone" class="sr-only">New phone number</label>
          <input type="text" name="phone" id="phone" class="form-control" placeholder="New phone number" />
        </fieldset>
        <fieldset class="form-group">
          <legend>Change Password</legend>
          <label for="old_password" class="sr-only">Old password</label>
          <input type="password" name="old_password" id="old_password" class="form-control" placeholder="Old password">
          <label for="password1" class="sr-only">New password</label>
          <input type="password" name="password1" id="password1" class="form-control" placeholder="New password" />
          <label for="password2" class="sr-only">Confirm new password</label>
          <input type="password" name="password2" id="password2" class="form-control" placeholder="Confirm new password" />
        </fieldset>
        <fieldset class="form-group">
          <legend>Identity Verification</legend>
          {% if not verification %}
          <label for="verification_document">Upload a document for identity verification: </label>
          <input type="file" name="verification_document" class="form-control" id="verification_document" />
          <label for="document_type">What type of document are you uploading?</label>
          <select name="document_type" id="document_type" class="form-control input">
            <option disabled selected>Choose One</option>
            <option value="student_id">Student ID Card</option>
            <option value="nid">National ID Card</option>
            <option value="birth_cert">Birth Certificate</option>
            <option value="passport">Passport</option>
            <option value="driving_license">Driving License</option>
          </select>
          {% else %}
            {% if verification.verified %}
              <p class="text-success"><i class="fa fa-check"></i> Identity is verified using your {{ verification.type }}</p>
            {% else %}
              <p>Verification pending. It may take upto 5 business days to verify your identity.</p>
            {% endif %}
          {% endif %}
        </fieldset>
        <input type="submit" value="Save changes" class="btn btn-dark" />
      </form>
    </div>
{% endblock content %}

tutor/templates/tutor/single_ad.inc.html
{% if feed.already_applied and display_url %}
<div class="ad border-success card" style="border-top-width: thick;">
  <div class="bg-success card-text text-light" style="padding: 0 10px;">
    <i class="fa-check fas"></i> Applied
  </div>
{% else %}
<div class="ad card">
{% endif %}
  <div class="card-body">
    <h4 class="card-title">
    {% if display_url %}
        <a class="card-link" href="{% url 'tutor-apply' feed.pk %}">{{ feed.title }}</a>
    {% else %}
        {{ feed.title }}
    {% endif %}
    </h4>
    <p class="card-text">{{ feed.description }}</p>
    <div class="row">
      <div class="col-md-6" title="Class and medium"><i class="fa fa-graduation-cap"></i> {{ feed.grade }} ({{ feed.type }})</div>
      <div class="col-md-6" title="Subjects"><i class="fa fa-book"></i> {{ feed.subjects }}</div>
    </div>
    <div class="row">
      <div class="col-md-6" title="Monthly salary"><i class="fa">৳</i> {{ feed.salary }}</div>
      <div class="col-md-6" title="Student gender and count"><i class="fa fa-user"></i> {{ feed.gender }} ({{ feed.std_count }} student(s))</div>
    </div>
    <div class="row">
      <div class="col-md-6" title="Date and time">
        <i class="fa fa-calendar-alt"></i>
        {{ feed.days }} days a week
        {% if feed.time %}
            ({{ feed.time }})
        {% endif %}
      </div>
      <div class="col-md-6" title="Location"><i class="fa fa-map-marked"></i> {{ feed.location }}</div>
    </div>
    <div class="row">
      <div class="col-md-12" title="Client name"><i class="fa fa-user-circle"></i>
          <a class="card-link" href="{% url 'tutor-profile' feed.client.pk %}">{{ feed.client.name }}</a>
          {% if feed.client.verification_set.first.verified %}
            <i class="text-info fas fa-check-circle" title="Verified client"></i>
          {% endif %}
      </div>
    </div>
    {% if show_feedback %}
      {% if not feed.feedback %}
        <a href="{% url 'tutor-feedback' feed.pk %}" class="btn btn-dark btn-small m-1">Provide feedback</a>
      {% else %}
        {% with feedback=feed.feedback %}
          {% include 'tutor/feedback.inc.html' %}
        {% endwith %}
      {% endif %}
    {% endif %}
  </div>
</div>

tutor/templates/tutor/tutor_profile.inc.html
    <style>
    .user-profile {
        margin: 10px 0;
    }
    .user-profile .user-image {
        height: 8rem;
        width: 8rem;
        border-radius: 50%;
    }

    #about div.collapse {
        display: block;
        height: 45px;
        overflow: hidden;
    }

    #about div.collapse.show {
        display: block;
        height: 100%;
        overflow: hidden;
    }

    #about div.collapsing[aria-expanded="false"] {
        height: 45px;
    }

    #about a.collapsed  {
        display: block;
        margin-top: 10px;
    }

    #about a.collapsed:after  {
        content: 'More';
    }

    #about a:not(.collapsed):after {
        content: 'Less';
    }
    </style>
    {% if editable %}
        <a href="{% url 'tutor-edit-profile' profile.pk %}">Edit profile</a>
    {% endif %}
    <div class="user-profile card">
      <div class="card-header">
        <table>
          <tr>
            <td style="padding-right: 15px">
              <img class="card-img user-image" src="/static/profile_imgs/{{ profile_img }}" alt="A portrait of {{ profile.name }}" />
            </td>
            <td>
              <h1 class="card-title">
                  {{ profile.name }}
                  {% if profile.verification_set.first.verified %}
                      <i class="text-info fas fa-check-circle" title="Verified tutor"></i>
                  {% endif %}
              </h1>
              <h6 class="card-text"><i class="fa fa-graduation-cap"></i> {{ profile.bio }}</h6>
              <h6 class="card-text"><i class="fa fa-map-marked"></i> {{ profile.location }}</h6>
              <h6 class="card-text"><i class="fa fa-user"></i> {{ profile.gender }}</h6>
            </td>
          </tr>
        </table>
      </div>
      <div id="about" class="card-body">
        <h4 class="card-title">{{ profile.title }}</h4>
        <div class="collapse" id="overview" aria-expanded="false">{{ profile.overview|linebreaks }}</div>
        <a role="button" class="collapsed" data-toggle="collapse" href="#overview" aria-expanded="false"
           aria-controls="overview"></a>
      </div>
      <div id="education" class="card-body">
        <h4 class="card-title hr">Education</h4>
        {% for edu in education %}
        <div class="card-text" style="margin-bottom: 10px">
          <h5 class="card-text">{{ edu.institute }}</h5>
          <h6 class="card-text small text-muted">{{ edu.degree }}, {{ edu.department }}</h6>
          <h6 class="card-text small text-muted">{{ edu.from_year|date:"Y" }} - {{ edu.to_year|date:"Y" }}, {{ edu.result }}</h6>
        </div>
        {% endfor %}
      </div>
      <div id="expertise" class="card-body">
        <h4 class="card-title hr">Expertise</h4>
        <p class="card-text">{{ profile.expertise}}</p>
      </div>
      <div id="work_history" class="card-body">
        <h4 class="card-title hr">Tuition History</h4>
      {% if work_history %}
        {% for work in work_history %}
        <div class="card">
          <div class="card-body">
            <table class="w-100">
              <tr>
                <td>
                  <h6 class="card-title">{{ work.ad.title }}</h6>
                  <p class="card-text small">{{ work.from_date|date:"M Y" }} - {{ work.to_date|date:"M Y" }},
                    {{ work.ad.std_count }} student(s), {{ work.ad.days }} days a week<br>
                    {{ work.ad.grade }} ({{ work.ad.type }}), {{ work.ad.subjects }}
                  </p>
                </td>
                <td class="text-right">Salary<br><i class="fa">৳</i>{{ work.ad.salary }}</td>
              </tr>
            </table>
            <div class="feedback">
              {% with feedback=work.ad.clientfeedback_set.first %}
                {% if feedback %}
                    <hr>
                    {% include 'tutor/feedback.inc.html' %}
                {% endif %}
              {% endwith %}
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <p>No history found.</p>
      {% endif %}
      </div>
    </div>

tutor/templates/tutor/view_profile.html
{% extends 'tutor/base_tutor.html' %}
{% load static %}

{% block content %}
{% include 'tutor/tutor_profile.inc.html' %}
{% endblock content %}